name: Build with Docker

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [ alpine, debian ]
        build: [ Debug, Release ]  # Build with debug symbols
        shmem: [ true, false ]     # Enable SHMEM API
        ssl: [ mbedtls, openssl ]  # Supported TLS libraries
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Containerized build
        run: |
          docker build -f Dockerfile.${{ matrix.distro }} --build-arg BUILD_TYPE=${{ matrix.build }} --build-arg SHMEM=${{ matrix.shmem }} --build-arg SSL=${{ matrix.ssl }} .

      # - name: Run Tests
      #   run: ctest --test-dir build --output-on-failure

