name: Valgrind Check

on: 
  - pull_request
  - workflow_dispatch

jobs:
  valgrind:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ssl: [ mbedtls, openssl ]  # Supported TLS libraries
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y valgrind cmake libconfig-dev libprotobuf-c-dev libconfig9 libprotobuf-c1 libssl3

      - name: Install Mbed TLS 3.x
        if: ${{ matrix.ssl == 'mbedtls' }}
        run: |
          curl -o mbedtls.tar.bz2 -L https://github.com/Mbed-TLS/mbedtls/releases/download/mbedtls-3.6.2/mbedtls-3.6.2.tar.bz2 && \
          tar -jxvf mbedtls.tar.bz2 && \
          cd mbedtls-* && \
          cmake -Bbuild -H. && \
          cmake --build build && \
          sudo cmake --install build

      - name: Config file
        run: |
          sed 's_/etc/umurmur/__g' umurmur.conf.example > umurmur.conf

      - name: Configure
        run: |
          cmake -B ./build-${{ matrix.ssl }} -H. -DCMAKE_BUILD_TYPE=Debug -DSSL=${{ matrix.ssl }} -DUSE_SHAREDMEMORY_API=true

      - name: Build
        run: |
          cmake --build ./build-${{ matrix.ssl }}

      - name: Run Valgrind
        uses: troxor/valgrind-action@v1.2.2
        with:
          binary_path: ./build-${{ matrix.ssl }}/bin/umurmurd
          binary_args: "-c umurmur.conf -d"
          xml_output_file: "valgrind-output.xml"
          timeout: 300s

      - name: Convert XML to SARIF
        uses: troxor/valgrind-sarif-action@v0.0.1
        with:
          xml_input_file: valgrind-output.xml
          sarif_output_file: valgrind-output.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: valgrind-output.sarif
          category: valgrind
